print("Welcome to Mad Libs!")
name1=input("Enter a name: ")
ship_name=input("Enter another name: ")
adjective1=input("Enter an adjective: ")
adjective2=input("Enter another adjective: ")
verb1=input("Enter a verb ending in -ing (EX: running): ")
verb2=input("Enter a past tense verb: ")
name2=input("Enter a third name: ")
adjective3=input("Enter a third adjective: ")
noun1=input("Enter a noun: ")
noun2=input("Enter a plural noun: ")
verb3=input("Enter a verb ending in -ed (EX: walked): ")

print("---Mad Libs: The Food Quest---")
print("There was once a person named "+name1+".")
print(name1+" was on a ship called "+ship_name+".")
print("\"Such a\\an "+adjective1+" ship!\" said one woman. She wasn't lying, the ship really was "+adjective2+".")
print("However, when "+name1+" was "+verb1+", the ship ran into a monster!!")
print("Everyone "+verb2+" as fast as they could, but then "+name1+" soon noticed that "+name2+" fell on the ground!")
print(name1+" quickly ran to save "+name2+", but the monster was too "+adjective3+"! It grabbed "+name2+" and was about to eat them!")
print(name1+", in the chaos, grabbed a "+noun1+" and threw it at the monster. The monster was so surprised that it let go of "+name2+" and ran away!")
print("The monster was defeated! And as people filed onto "+noun2+", they all "+verb3+" for "+name1+"! In the end, everyone lived happily ever after.")
print("(Except for the monster, it died.)")
